runtime: nodejs20
env: standard

instance_class: F1

handlers:
  - url: /(.*\.(js|css|png|jpg|jpeg|svg|woff|woff2))
    static_files: dist/\1
    upload: dist/(.*)
    secure: always
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
